### ISSUE TITLE
Add apps filtering to URL query parameters

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/web-ui#139]
Sometimes I would like to send a pre-filtered URL to people, e,g, "This are the players that support sat streaming: <url>".

For that, it would be useful to represent the selected filters in the URL (i.e. as query parameters).

References:
- https://www.kindacode.com/article/react-router-uselocation-hook-tutorial-and-examples/
- https://thewebdev.info/2020/07/26/how-to-use-url-parameters-and-query-strings-with-react-router/

**Comment by daveajones** [comment]
I actually wanted this the other day as well. Good idea.

**Comment by dellagustin** [comment]
I'm 70% confident I can implement it, let's see, worst case scenario, I'm doing some refactoring to the apps page that should at least pave the road a bit to introduce this feature.

**Comment by dellagustin** [comment]
Implemented with #145 and it is already live:
![image](https://user-images.githubusercontent.com/260113/156060796-f920adbe-7646-4355-b724-542d22b1ba63.png)
