### ISSUE TITLE
API calls don't work on local machine

### ISSUE THREAD

**Issue by stevencrader** [Podcastindex-org/web-ui#14]
I may be doing something wrong, but I can't get the API calls to work when running locally. I've created a .env file with my keys but it always fails.

Here is the error that is shown in the terminal after running `yarn start`

    [HPM] Error occurred while trying to proxy request /api/recent/episodes?max=7 from localhost:9001 to http://localhost:5001 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by stevencrader** [comment]
@drunkplato do you know what I need to do to make the API calls resolve on my local PC?

**Comment by stevencrader** [comment]
I figured out the issue. I wasn't also running `node server.js`. I was just running `yarn start`.

**Comment by daveajones** [comment]
Sorry I’m no help here Steven. I’ve barely dug into this code. I just pulled it and ran it. Lol.

**Comment by drunkplato** [comment]
I should probably add to the `start` script the starting of the node server as well. Essentially it is built with the `server.js` reverse proxy to avoid CORS issues. I will also update the `README.md`
