### ISSUE TITLE
Apps: Add "comments" to supported elements filter / features

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/web-ui#154]
Currently supported by podfriend and podverse.
Might be interesting to also add [Minipub](https://github.com/skymethod/minipub) and the other project from John that I cannot remember the name right now.
cc @johnspurlock-skymethod

**Comment by ericpp** [comment]
It looks like Social Interact was added as a filterable element in #192

**Comment by dellagustin** [comment]
@ericpp , thanks, I see it in the UI now: 
![image](https://user-images.githubusercontent.com/260113/214951934-46aa2051-c353-4200-9664-c5b5e1ec0400.png)

**Comment by stevencrader** [comment]
Can this be closed?

**Comment by dellagustin** [comment]
@daveajones this can be closed.
Although, we might consider whether it should remain as "Social Interact" or be renamed to "Comments", since it is the primary usage of the tag, and possibly something people would understand more easily when using the list.

**Comment by dellagustin** [comment]
I'll close from my side and leave the renaming as an idea.
