### ISSUE TITLE
Font size for stats too big on mobile; causing horizontal scroll

### ISSUE THREAD

**Issue by stevencrader** [Podcastindex-org/web-ui#18]
See report: https://podcastindex.social/web/statuses/105108411917629302

**Comment by amorphous** [comment]
OK - sorry - got to a laptop now.
This is on a Moto g7 Power - 1520x720
although the screen is listed at 720px - it seems to show as if the resolution has a width of 447 (if I adjust the width (debuggin in FFox her on the laptop)
I'm not sure whether the font size should be reduced more at the change at 520px - as without this being smaller there would need to be another at 490 (where the last digit of the 'total podcasts' starts to break out beyond the border). My tiny bit of un-educated hacking makes it look like it's good if the '72px !important' is changed to 60px !important like this:

```
inline:56 @media only screen and (max-width: 767px)
.kpi-massive-value {
    font-size: 60px !important;
```
that does seem to cover it until it gets down to 440px.. which should cover most likelyhoods...

I'm no pro... but given the 'kpi-massive-value' class name, I'm not expecting it to affect anything else(!) :D

**Comment by daveajones** [comment]
Thanks for this.  Sorry for the radio silence.  Back on this now and will try to make this fix.
