### ISSUE TITLE
The Mastodon profile link 404s

### ISSUE THREAD

**Issue by zoul** [Podcastindex-org/web-ui#193]
The “Follow us on Twitter or Mastodon” footer line links here:

https://noagendasocial.com/@podcastindex

But that’s a 404.

**Comment by ericpp** [comment]
The last post when it existed seems to have been from 2020: https://web.archive.org/web/20220614235344/https://noagendasocial.com/@podcastindex

I wonder if it got deleted as a stale account during the annual noagendasocial purge.

**Comment by ericpp** [comment]
Looks like @daveajones fixed this with 4d60511d32351256691d2267cf8f1abb325d4672
