### ISSUE TITLE
podbean.com feeds not supported?

### ISSUE THREAD

**Issue by fapdash** [Podcastindex-org/web-ui#203]
Sorry if this is the wrong repository to report, I'm not really sure where to report this.

We tried to add a podcast feed to podcastindex.org, but it seems to find no episodes.
Are podbean.com feeds not supported or is this a bug?

Podbean feed: https://feed.podbean.com/exercism/feed.xml
Podcastindex: https://podcastindex.org/podcast/5811797

**Comment by fapdash** [comment]
@stevencrader Thank you for confirming so quickly.

I also tried to ask about this via an email to [info@podcastindex.org](mailto:info@podcastindex.org) and the email bounced with
```
 Sender address rejected: SPF fail - not authorized (in
    reply to RCPT TO command)
```
Looks like the email should be forwarded to another email address but the setup is broken.

**Comment by stevencrader** [comment]
Dave is the guy that woild fix that also. Thanks

**Comment by stevencrader** [comment]
Whatever the issue, it seems to have resolved itself.
