### ISSUE TITLE
Removing a Podcast

### ISSUE THREAD

**Issue by iamflorencejay** [Podcastindex-org/web-ui#205]
I am an owner and would like to remove this podcast because we changed my provider.

https://podcastindex.org/podcast/1194671

Thanks.

**Comment by stevencrader** [comment]
From looking, it seems you are using Acast now. Is that correct?

If so, @daveajones can you mark the Anchor https://podcastindex.org/podcast/1194671 a duplicate of the Acast https://podcastindex.org/podcast/5923211 ?

**Comment by iamflorencejay** [comment]
yep

**Comment by stevencrader** [comment]
@daveajones can you add this your TODO?
