### ISSUE TITLE
Add support for comments

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/web-ui#213]
## Dependencies
- the content of the socialInteract tag must be returned by the API
    - https://github.com/Podcastindex-org/docs-api/issues/91 

## Remarks
- Might be better if we implement a view for individual episodes

## References
- https://www.npmjs.com/package/threadcap
- https://github.com/podStation/podStation/issues/304

**Comment by dellagustin** [comment]
As far as I can tell the API is not returning the content socialInteract tag:
![image](https://user-images.githubusercontent.com/260113/213022975-008e4b16-7676-494f-8a9a-60b158cc020d.png)

**Comment by daveajones** [comment]
This probably needs to be an issue on the api repo. I’ll add.

**Comment by dellagustin** [comment]
One of the challenges here will be CORS (as always), we will need to proxy the requests to fetch the comments on the server side.
