### ISSUE TITLE
Anchor-based podcast not playing on podcastindex or apps connected to the index

### ISSUE THREAD

**Issue by godSaysHODL** [Podcastindex-org/web-ui#216]
My girlfriend has a writers podcast called "Good On Paper"

She originally had it hosted on RSS.com, but switched to anchor to save money. Since then, the podcast has stopped playing on podcastindex-using apps, such as the podcastindex.com player, Fountain, and Podverse. 

I tried to work around this by using an IPFS feed, but that didn't play either and subsequently there are two of her podcasts on the index now, with neither able to play.

Please help us 🙏

**Comment by stevencrader** [comment]
Using the new dashboard I was able to resolve this. 

Now the only show that is in the index is https://podcastindex.org/podcast/5974918 which is hosted by Anchor.

**Comment by godSaysHODL** [comment]
Thank you so much. Closing issue
