### ISSUE TITLE
Performance improvement for displaying comments

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/web-ui#228]
This is a leftover of https://github.com/Podcastindex-org/web-ui/pull/218.

**Comment by dellagustin** [comment]
I started doing some tests, looks feasible - @nathangathright , I might ask for some support with design related changes for this, as comments will show up progressively in the UI while they are loaded on the back-end.

**Comment by ericpp** [comment]
You can get a speed increase by using the Mastodon API over the ActivityPub API when available, see: https://github.com/ericpp/podcastindex-web-ui/commit/45bc2cfb2723b7220c9294e9031a3aa210905c20

The Mastodon API uses two calls to get everything:
https://podcastindex.social/api/v1/statuses/109881536907227002
https://podcastindex.social/api/v1/statuses/109881536907227002/context

Whereas the ActivityPub API only gives you direct replies to the root post and requires you to get replies to replies separately:
https://podcastindex.social/users/dave/statuses/109881536907227002
https://podcastindex.social/users/dave/statuses/109881536907227002/replies?only_other_accounts=true&page=true
https://podcastindex.social/users/alvaro/statuses/109881679521959292/replies?only_other_accounts=true&page=true
https://podcastindex.social/users/alvaro/statuses/109881719981672487/replies?only_other_accounts=true&page=true
https://podcastindex.social/users/Drebscott/statuses/109882219344388312/replies?only_other_accounts=true&page=true

The ActivityPub API also doesn't provide avatars, which requires additional calls to the user page of each commenter:
https://podcastindex.social/users/dave
https://podcastindex.social/users/alvaro
https://podcastindex.social/users/Drebscott

**Comment by nathangathright** [comment]
If we wanted to add a reply button for each post, I’ve just discovered some URL methods that should make that very straightforward.

1. Visitor clicks Reply on a given Mastodon post
2. Site displays dialog requesting their home instance
3. Visitor enters their instance URL
4. Site redirects visitor to: `https://${visitorInstance}/authorize_interaction?uri=${postURL}`

**Comment by dellagustin** [comment]
@nathangathright , that's more a comment for https://github.com/Podcastindex-org/web-ui/issues/233

**Comment by dellagustin** [comment]
@ericpp that's an interesting alternative. I have mixed feelings, as this kid of hides the limitations of AP as a Client-to-Server API.
At the end, the standard is based on AP.
I need to do some investigation about that.
Anyway, if we use it, maybe it would be better if that is added to threadcap directly instead.
@johnspurlock-skymethod, I'd like to have your thoughts on this topic.

**Comment by johnspurlock-skymethod** [comment]
Threadcap actually includes Mastodon API code already - it falls back to it when the AP replies collection is unimplemented (cough Pleroma).  I also tend to agree we should stick to AP whenever possible.

Note that when enumerating a thread with Threadcap, you need to provide a `Cache` implementation.  This is so you can do smart server-side caching instead of doing everything on every client from scratch every time.  Since this will differ from backend to backend it is up to you to provide an implementation of the interface (or use the `InMemoryCache`, which only lives for the duration of the calling isolate).

You might consider doing all of the comment fetching server-side, so results can be cached on your side and shared for subsequent calls.  Completely up to you.

**Comment by dellagustin** [comment]
I sent a PR that implemented an optimization by pushing comments back to the UI as soon as threadcap loads their responses (just the list of responses, not body): https://github.com/Podcastindex-org/web-ui/pull/236

**Comment by dellagustin** [comment]
@ericpp , I'm still interested in using the Mastodon API as performance optimization, but since the index is kind of a "reference implementation", I'd prefer to keep it as close to AP as possible.

**Comment by ericpp** [comment]
@dellagustin Makes sense to me. I agree that making this work with AP is the best option and ensures compatibility with all possible commenting systems.

**Comment by dellagustin** [comment]
This was implemented with https://github.com/Podcastindex-org/web-ui/pull/236, aside of adding server side (persistent?) caching, this is as good as it gets, so I'm closing the issue.
