### ISSUE TITLE
Leftover identified on code review of PR #218

### ISSUE THREAD

**Issue by dellagustin** [Podcastindex-org/web-ui#232]
See https://github.com/Podcastindex-org/web-ui/pull/218#discussion_r1103688378.

Low priority. It is only a sanity check and it is not failing when all is working.

@daveajones , you can assign this one to me.

**Comment by dellagustin** [comment]
will be fixed with https://github.com/Podcastindex-org/web-ui/pull/266.

**Comment by stevencrader** [comment]
Can this be closed?

**Comment by dellagustin** [comment]
Yes, thank you @stevencrader the reminder.
