### ISSUE TITLE
Index search does not work correctly for non-latin languages

### ISSUE THREAD

**Issue by AmitAronovitch** [Podcastindex-org/web-ui#270]
This is apparently a problem in the API backend server (let me know if there is a more suitable project to report this).

Basically, searching by term (both `search?term=` and `search/byterm?q=`) does not work (does not find any result) when the term searched is a word in a non-latin script, even when valid results are known to exist in the index.

Note: searching by the full title (`search/bytitle?q=`) does find the correct result.

Examples:
```bash
~$ curl -s "https://api.podcastindex.org/search?term=רברס" | jq -r .resultCount
0
~$ # itunes does find it :
~$ curl -s "https://itunes.apple.com/search?media=podcast&entity=podcast&term=רברס" | jq -r .resultCount
1
```
This podcast can be found correctly in authenticated podcastindex query: `https://api.podcastindex.org/api/1.0/search/bytitle?q=רברס+עם+פלטפורמה` (supposing the authentication tokens are properly added).

**Comment by AmitAronovitch** [comment]
This might be caused by some problem in the fulltext-search index generation or the bindings argument passing of the db driver (something wipes out non-ascii characters, or does not handle unicode properly).

I do not have access to the relevant code, but I made some experiments with the latest db-dump (created FTS index in native sqlite3), and verified that the data is there.

(To repeat the result below, you can usel the [podcastindex_db script](https://github.com/AmitAronovitch/podcastindex_database/tree/db_script#install-using-docker). It is convenient for downloading updated db-dumps, preparing search-index, and searching)

```
$ podcastindex_db search רברס
(1070226, '173e7e46-71f2-5940-b761-64ad6a5e4cb8', 'רברס עם פלטפורמה')
$ podcastindex_db search بيتكوين
(2453224, '37dd4e7b-70fc-5781-97ea-ce46cdb2fb9c', 'توقعات بيتكوين الإسبوعية')
(4630178, 'a894d5cb-2af2-5de0-a50a-abdb279f3b53', 'Bitcoin بالعربي')
(5574008, '8c43b90e-1b35-5a38-b440-dd08bf6a6138', 'برق نت')
$ podcastindex_db search --fields title "חיות כיס"
(1115138, '2b6098b1-1459-5c68-b034-73dd7713664e', 'חיות כיס Hayot Kiss')
(1914876, '33b67ef5-2a7b-5876-8e99-588339087be8', 'חיות כיס Hayot Kiss')
(1946766, '5733cfc6-8873-5e27-8b0d-33771ea76975', 'חיות כיס Hayot Kiss')
$ # The above seems to be a triplicate!?
```

**Comment by AmitAronovitch** [comment]
Following are some stats, to figure out the scope of this issue:

total 4091595 in DB
total non-latin podcasts: 152212, which is 3.72%
Top 30 language codes, by podcast counts:
|    | NL   | code   |   podcasts |   percent |
|---:|:-----|:-------|-----------:|----------:|
|  0 |      | en     |    1589164 | 38.8397   |
|  1 |      | en-us  |     453347 | 11.08     |
|  2 |      | es     |     395365 |  9.66286  |
|  3 |      | pt     |     195589 |  4.78026  |
|  4 |      | es-ES  |     190738 |  4.6617   |
|  5 |      | en-US  |     129453 |  3.16388  |
|  6 |      | in     |     109669 |  2.68035  |
|  7 |      |        |      69553 |  1.6999   |
|  8 |      | de     |      66829 |  1.63332  |
|  9 |      | fr     |      64880 |  1.58569  |
| 10 |      | pt-br  |      61261 |  1.49724  |
| 11 |      | it     |      58158 |  1.4214   |
| 12 |      | id     |      33402 |  0.816356 |
| 13 |      | es-mx  |      32798 |  0.801594 |
| 14 |      | en-gb  |      31819 |  0.777667 |
| 15 | *    | ja     |      30278 |  0.740005 |
| 16 |      | hi     |      28975 |  0.708159 |
| 17 | *    | ru     |      27144 |  0.663409 |
| 18 | *    | ar     |      22967 |  0.561321 |
| 19 | *    | tr     |      21176 |  0.517549 |
| 20 | *    | zh     |      20187 |  0.493377 |
| 21 |      | nl     |      19351 |  0.472945 |
| 22 | *    | zh-cn  |      16006 |  0.391192 |
| 23 | *    | pl     |      14454 |  0.353261 |
| 24 |      | de-de  |      11398 |  0.278571 |
| 25 |      | sv     |      11305 |  0.276298 |
| 26 |      | ca     |      10754 |  0.262831 |
| 27 |      | es-ar  |      10304 |  0.251833 |
| 28 |      | de-DE  |      10138 |  0.247776 |
| 29 |      | en-au  |      10058 |  0.245821 |

**Comment by AmitAronovitch** [comment]
I have no previous experience with Sphinx search, but I am willing to try, and will surely share if I have any success.

**Comment by daveajones** [comment]
Great!  I’ll post our sphinx config for you to use.

**Comment by AmitAronovitch** [comment]
Meanwhile, I verified that the search for non-latin podcasts actually does work correctly in manticore if you use the default config that comes with the manticore docker file (and import the data directly with a huge sql script). Procedure to repeat this test is listed below.

The problem might be in the way the data is imported into manticore, or even in the way in which the search terms from the api are passed into the db (mysql driver?)).

Test:
1. Prepare the directory and get the data
```shell
mkdir mtc-test
cd mtc-test
mkdir data
mkdir etc
wget https://gist.github.com/AmitAronovitch/0ebb3c50df19d7086e02b4cff59cb8d1/raw/ea31526da0f5e6ed6011b9272ec8b36b732438d6/docker-compose.yml
```
2. Download and unpack the data
```shell
wget https://amit-public.s3.eu-west-1.amazonaws.com/pi_test/local.tar.gz
tar -zxvf local.tar.gz
```
3. Run the server and import the data (this might take some time...)
```shell
docker compose up -d
docker compose exec manticore mysql
mysql> source /mnt/local/mtc-db-table.sql
mysql> source /mnt/local/mtc-db-data.sql
mysql> \q
```
4.  Test search + shut down the server
```shell
~ $ docker compose exec manticore mysql
mysql> SELECT * FROM podcasts WHERE MATCH('רברס');
+---------+--------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| id      | title                          | description                                                                                                                  |
+---------+--------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 1070226 | רברס עם פלטפורמה               | רברס עם פלטפורמה הוא הפודקאסט הגדול והותיק ביותר למפתחי תכנה בעברית                                                          |
+---------+--------------------------------+------------------------------------------------------------------------------------------------------------------------------+
mysql> SELECT * FROM podcasts WHERE MATCH('بيتكوين');
+---------+------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id      | title                                          | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+---------+------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5574008 | برق نت                                         | برق نت هو بودكاست تحت مظلة قناة (بيتكوين 21) يهتم بنشرثقافة البيتكوين وإثراء المحتوى العربي في هذا البودكاست راح نناقش البيتكوين ونصحح بعض المفاهيم الخاطئة لكي تبني تصور صحيح عن هذا الأصل المالي : حسابتنا على مواقع التواصل https://linktr.ee/bitcoin21                                                                                                                                                                                                                                                                                                                     |
| 4630178 | Bitcoin بالعربي                                | بيتكوين بالعربي هو مشروع تحت مظلة شركة اس بي اكس نهدف من خلاله لزيادة وعي الناس بالبيتكوين و اثراء الناس قدر المستطاع عن طريق خلق محتوى عربي بالكامل. سوف نبدأ حوار مع المتخصصين عن البيتكوين و تسليط الضوء على جانب جديد منه في كل حلقةهذا البرنامج مقدم من شركة اس بي اكسhttps://twitter.com/sbxdotxyzhttps://instagram.com/sbxdotxyz https://sbx.xyz                                                                                                                                                                                                                        |
| 2453224 | توقعات بيتكوين الإسبوعية                       | أسواق كريبتو تقوم بتقديم تحليلات و توقعات اسبوعية لعملة البيتكوين https://www.aswaqcrypto.com                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+---------+------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
mysql> \q
~ $ docker compose down --remove-orphans
[+] Running 2/2
 ✔ Container manticore       Removed                                                                                                                               0.5s 
 ✔ Network mtc-test_default  Removed                                 
```

**Comment by AmitAronovitch** [comment]
seems like I have been barking up the wrong tree 🤦

```
$ curl -s "https://itunes.apple.com/search?media=podcast&entity=podcast&term=%D7%A8%D7%91%D7%A8%D7%A1" | jq -r .resultCount
1
```

So we just need to fix the url-encoding to support  percent-escaping non-asciis. I guess I did file this issue on the correct project after all :-)

(BTW - maybe the API backend should be fixed as to support unescaped non-ascii, like apple's endpoint)

**Comment by daveajones** [comment]
Starting work on this now.  Thanks for all the effort you have given to help track this down and test.

**Comment by daveajones** [comment]
Fixed!

https://podcastindex.org/search?q=%D7%A8%D7%91%D7%A8%D7%A1

**Comment by AmitAronovitch** [comment]
Thanks :-)

This appears to be solved on the backend (my original query in the description of the issue works now).

But as far as I could tell by following the code from this project, the requests sent by the frontend actually *should* get %-coded correctly before being sent to the index (the proxy server [passes](https://github.com/Podcastindex-org/web-ui/blob/9e9fac24fcd446fe1afb4feab4fee3bc4716688a/server/index.js#L80) the hebrew term to the `custom` function from `podcast-index-api` package, which then, in turn [passes it](https://github.com/comster/podcast-index-api/blob/3145f300b72cf9048fd833fb14f134b07fa98a8b/index.js#L90) through `querystring.stringify` (which should encode it correctly by default) before submitting. Debugging seems to confirm that.

So I still do not understand what was causing the problem exactly (i.e. what exactly in the requests that the UI is sending to the backend was causing them to fail).

I am closing this,  since everying works fine now, but if anyone knows the answer to this mystery - I'd appreciate a clue ...

**Comment by AmitAronovitch** [comment]
Thanks :-)

This appears to be solved on the backend (my original query in the description of the issue works now).

But as far as I could tell by following the code from this project, the requests sent by the frontend actually *should* get %-coded correctly before being sent to the index (the proxy server [passes](https://github.com/Podcastindex-org/web-ui/blob/9e9fac24fcd446fe1afb4feab4fee3bc4716688a/server/index.js#L80) the hebrew term to the `custom` function from `podcast-index-api` package, which then, in turn [passes it](https://github.com/comster/podcast-index-api/blob/3145f300b72cf9048fd833fb14f134b07fa98a8b/index.js#L90) through `querystring.stringify` (which should encode it correctly by default) before submitting. Debugging seems to confirm that.

So I still do not understand what was causing the problem exactly (i.e. what exactly in the requests that the UI is sending to the backend was causing them to fail).

I am closing this,  since everying works fine now, but if anyone knows the answer to this mystery - I'd appreciate a clue ...

**Comment by daveajones** [comment]
Thanks so much for your help on this. Truly appreciated.
