### ISSUE TITLE
Change feed or remove and add new one.

### ISSUE THREAD

**Issue by Krotosz6** [Podcastindex-org/web-ui#273]
Hi. I moved from Anchor to Castopod. I made redirection to all feeds. In the Itunes and Google databases, I could change the feed field to a new one. Unfortunately, podcasts have not updated in PodcastIndex. I tried to add myself. One I succeeded and now it is duplicated, but the old one feed does not display new episodes. However, in another one somehow incorrectly added and shows a blank page. Please help. Below are the relevant links.

Old feeds ready to remove:
1. [https://anchor.fm/s/8892a58/podcast/rss](https://anchor.fm/s/8892a58/podcast/rss)
2. [https://anchor.fm/s/16b25f78/podcast/rss](https://anchor.fm/s/16b25f78/podcast/rss)
3. [https://anchor.fm/s/66b1d800/podcast/rss](https://anchor.fm/s/66b1d800/podcast/rss)

New feeds:

ad. 1 Doesn't work only in PodcastIndex: [https://castopod.warroza.pl/@radiowarroza/feed.xml](https://castopod.warroza.pl/@radiowarroza/feed.xml)
ad. 2 Now it's added but duplicated: [https://castopod.warroza.pl/@pszczelewiesci/feed.xml](https://castopod.warroza.pl/@pszczelewiesci/feed.xml)
ad. 3: [https://castopod.warroza.pl/@ojciecisyn/feed.xml](https://castopod.warroza.pl/@ojciecisyn/feed.xml)

Thanks.

**Comment by stevencrader** [comment]
Hi @Krotosz6 

Before making any changes, I want to verify what you are asking.

- [x] Title: "Radio Warroza Pszczele Wieści"
  - Old Feed: https://anchor.fm/s/8892a58/podcast/rss
  - New Feed: https://castopod.warroza.pl/@radiowarroza/feed.xml
  - Index: https://podcastindex.org/podcast/651249
  - This one has already combined the 2 feeds
- [x] Title: "Pogadanki o pszczołach"
  - Old Feed: https://anchor.fm/s/16b25f78/podcast/rss
    - This isn't in the index
    - I see Anchor redirects to https://castopod.warroza.pl/@pszczelewiesci/feed.xml now
  - Feed: https://castopod.warroza.pl/@pszczelewiesci/feed.xml
  - Index: https://podcastindex.org/podcast/6428673
- [ ] Title: "Ojciec i syn"
  - Old Feed: https://anchor.fm/s/66b1d800/podcast/rss
  - New Feed: https://castopod.warroza.pl/@ojciecisyn/feed.xml
  - Old Index: https://podcastindex.org/podcast/4150337
  - New feed is not in index

So it looks like the only change is to fix the url for "Ojciec i syn". If that is correct, we can make the change.

**Comment by Krotosz6** [comment]
That's correct. Thanks :)

Jakub Jaroński




17 lip 2023, 01:04 od ***@***.***:

**Comment by daveajones** [comment]
I’ll get it handled.

**Comment by Krotosz6** [comment]
thanks :)

Jakub Jaroński




17 lip 2023, 13:41 od ***@***.***:
