### ISSUE TITLE
Add "Fediverse" platform to apps page filter tags

### ISSUE THREAD

**Issue by Agorise** [Podcastindex-org/web-ui#287]
Fediverse is a platform, just like Hive. 
It enables Podcasters to syndicate their podcasts out to federated peertube, funkwhale and other streaming Hosts. For example, the CastGarden host syndicates podcasts to both the Hive network, as well as the fediverse network, vastly increasing the number of subscribers/followers that a Podcaster can get: 
https://cast.garden/about/follows

**Comment by Marzal** [comment]
If I have understood correctly,  you have to add Fediverse to platform in each app info, and into https://github.com/Podcastindex-org/web-ui/blob/4439c59563fca7a394754da294870d09f162b732/server/data/apps-schema.json#L56, if this is correct, I don't mind making a PR if this new platform  is accepted

**Comment by ericpp** [comment]
@Marzal Yep. You would just add "Fediverse" to the `platforms` array in `apps-schema.json` file and then update the `platforms` array in `apps.json` to use it: https://github.com/Podcastindex-org/web-ui/blob/4439c59563fca7a394754da294870d09f162b732/server/data/apps.json#L2740-L2744

**Comment by Marzal** [comment]
Should this new platform be only for apps which natively supports the Fediverse (Peertube, CastGarden) ? Or also for apps that supports ActivityPub in the Socialinteract tag (Podverse for example)?

**Comment by Agorise** [comment]
All Fediverse platforms utilize the activitypub protocol. See fediverse.party website for examples

**Comment by Agorise** [comment]
Side question: 
Where is this "Synchronize" element defined? 
https://podcastindex.org/apps?elements=Synchronize

**Comment by Agorise** [comment]
> If I have understood correctly, you have to add Fediverse to platform in each app info, and into
> , if this is correct, I don't mind making a PR if this new platform is accepted

If you could add Fediverse to both apps.json (CastGarden) and apps-schema.json @Marzal that would be MUCH appreciated. I am not github savvy at all. Please and thank you :)

**Comment by Marzal** [comment]
That's no problem, the thing is to first agree with the more experienced contributors, what would be the scope of the platform. As I was asking before, it's not the same an app that creates content in the Fediverse, that another that only can read the posts.  So I would say Peertube and CastGarden sure, Podverse and any other with support for ActivityPub in the Socialinteract tag, also yes. But more experienced inputs would be needed in my opinion for this second case.

PD: I really like the proposal

**Comment by Agorise** [comment]
I see Fediverse on the apps page now, thank you! :) 
Closing this issue.
