### ISSUE TITLE
Add missing Supported Elements filter tags on apps page

### ISSUE THREAD

**Issue by Agorise** [Podcastindex-org/web-ui#288]
Please add the following filter tags to apps page Supported Elements: 
1. "Podroll" (this is a major value-add for Podcast Hosts)
2. alternate enclosure > "Source" (this is important to show which apps support Torrents, IPFS, Tor, Lokinet, I2P, etc) 
3. alternate enclosure > "Integrity" (this is important for media file verification in many organizations/corporations) 
4. "Tracker" (very important when offering streaming site links, especially when using activitypub protocol)  
 
Example of usage: 
https://cast.garden/feeds/podcast/videos.xml?videoChannelId=37

**Comment by Marzal** [comment]
Hi, my 2 cents:
> Please add the following filter tags to apps page Supported Elements:
> 
>     1. "Podroll" (this is a major value-add for Podcast Hosts)
> 
Already added
>     2. alternate enclosure > "Source" (this is important to show which apps support Torrents, IPFS, Tor, Lokinet, I2P, etc)
> 
`podcast:source` is required in the `AlternateEncousure` so the tag/element implies `source` [1](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#source)
>     3. alternate enclosure > "Integrity" (this is important for media file verification in many organizations/corporations)
> 
This is optional so it would require that each host, player, etc reported if supports it. If there is an agreement that PI wants so much detail in the list
>     4. "Tracker" (very important when offering streaming site links, especially when using activitypub protocol)
> 
This is tag is not in the namespace, so you would need to make a official proposal fisrt.
