### ISSUE TITLE
New 'type' column for apps page

### ISSUE THREAD

**Issue by keunes** [Podcastindex-org/web-ui#29]
Adding AntennaPod to the apps page I thought we held the open source podcast manager app monopoly and was surprised to see other 'apps'. One I tried appeared to be a web app - what a relief :p

As (hopefully) more and more platforms and apps integrate with Podcast Index, it will be helpful as a user to filter for a specific type you're looking for.
I wanted to propose therefore a new 'type' column with the following possible values:
* webapp
* Android app
* iOS app
* Desktop application
* Hosting platform
* Directory

Desktop could ofc be specified further (Linux/Windows/Mac), but may be unnecessary for the (long) time being.

Then filtering based on this column could be added as a later improvement. For now it'd already be great to start collecting structured data.

**Comment by benflap** [comment]
I created pull request #30 and it does have something like this. I spit your idea of “type” in two:
- appType (app, hosting, or directory)
- platforms (Android, iOS, Web, etc)

I put `appType` right below the app name and platforms in its own column.
The problem with this approach is that hosting companies don’t necessarily have a platform so I just gave them the platform of "N/A"

**Comment by daveajones** [comment]
We’re discussing some structural stuff on the site tomorrow. I’ll update here when we discuss.

**Comment by brianoflondon** [comment]
I'd love to see AppType be used as a way of grouping the entries on this page. I'm looking at the source and I'd love to learn how to do it... but I really shouldn't!

**Comment by dellagustin** [comment]
@keunes , anything still missing your?
Currently, it is possible to filter for specific type and platform:
![image](https://user-images.githubusercontent.com/260113/221436173-78476ee8-4983-4154-8472-ac25411381e4.png)

**Comment by keunes** [comment]
Thanks @dellagustin for the ping. Closing!
