### ISSUE TITLE
Can't search on mobile Chromium-based browsers

### ISSUE THREAD

**Issue by joksas** [Podcastindex-org/web-ui#293]
When searching for a podcast on mobile, pressing <kbd>Enter</kbd> (or whatever that bottom-right key is called) focuses the search type wrapper div instead of performing the search. In fact, I couldn't figure out how to do the search.

Reproduced on mobile Brave (Android) and mobile Chrome (Android). The search works fine on mobile Firefox (Android), desktop Brave (Linux), and desktop Firefox (Linux).

**Comment by stevencrader** [comment]
Thanks. I see the same behavior. I'll work on a fix.
