### ISSUE TITLE
Duplicate feed but correct version not updating

### ISSUE THREAD

**Issue by mattstratton** [Podcastindex-org/web-ui#321]
Hi! Somehow my show is in here twice:

- https://podcastindex.org/podcast/2108724 (Points to the RSS feed on blubrry, which is not the correct feed for the show)
- https://podcastindex.org/podcast/1039729 (points to the correct RSS feed on arresteddevops.com, but it's very out of date)

Not quite sure if an issue is the right way to raise this, but giving it a shot :)

**Comment by stevencrader** [comment]
I kicked the https://podcastindex.org/podcast/1039729 version and marked the other as a duplicate.

Thanks for reporting it.

**Comment by stevencrader** [comment]
@daveajones the index is showing some duplicate episodes now. Will those resolve? They are not duplicated in the XML.

**Comment by daveajones** [comment]
You probably want to do a "reset" on it to clear out the old stuff and have it pull a fresh feed.

**Comment by backache** [comment]
Could we have a simple mechanism on the front-end for fixing (or just reporting) dupe's 

One I came across can be seen with https://podcastindex.org/search?q=somewhere%20on%20earth&type=all

and is both [6661055](https://podcastindex.org/podcast/6661055) and [6711174](https://podcastindex.org/podcast/6711174)

**Comment by stevencrader** [comment]
Resolved.
