### ISSUE TITLE
Add Chapters to the CastGarden listing

### ISSUE THREAD

**Issue by Agorise** [Podcastindex-org/web-ui#337]
Hi, sorry I was unsure on how to do a Pull request, so I am posting this request here, please feel free to move this request if needbe :) 
 
[CastGarden](https://podcastindex.org/apps?appTypes=blockchain&platforms=Fediverse) now supports the Chapters element. 
 
An example podcast: 
https://cast.garden/w/3igmTN3LAHfW4CNetPH7jS 
 
The RSS: 
https://cast.garden/feeds/podcast/videos.xml?videoChannelId=35 
 
Please add the Chapters element to the CastGarden listing. 
Thank You! :)

**Comment by Marzal** [comment]
Hi, normally when adding a new feature, a link is also provided to "the announce" or "a blog post showing how to use" or "the source code repo".

**Comment by Agorise** [comment]
Aaah yes @Marzal , here is the link to the repo: 
https://www.npmjs.com/package/peertube-plugin-hive-tube?activeTab=code 
 
Hive-Tube is the software which runs the CastGarden podcast hosting platform.
