### ISSUE TITLE
Podcast not being updated

### ISSUE THREAD

**Issue by bclouthier** [Podcastindex-org/web-ui#342]
Hi,
I have a podcast at [refined90scinema.com](url) since August, my podcast hasn’t been updating on the Index. Using Podverse to listen, the newest episode isn’t showing up. I’ll try adding another episode to the backend and see if it pulls it. Any help would be appreciated.

**Comment by stevencrader** [comment]
Hi. I've requested a manual re-scan and the latest  info is now in the index. It will take a few more minutes before Podverse pulls it in.

**Comment by bclouthier** [comment]
Thank you! If this happens in the future, is there a more-proper mechanism to get a re-scan.

**Comment by stevencrader** [comment]
This is fine. We don't really have a dedicated way to report these.

**Comment by Marzal** [comment]
> Thank you! If this happens in the future, is there a more-proper mechanism to get a re-scan.

I think you have 2 alternative options:

- Podping
- In Mastodon post a toot with: rescan taging the podcast_index_id@ap.podcastindex.org of your podcast

**Comment by dhk2** [comment]
Shouldn't https://api.podcastindex.org/api/1.0/hub/pubnotify?id=149168&pretty be a third option?

https://podcastindex-org.github.io/docs-api/#get-/hub/pubnotify
