### ISSUE TITLE
Is the blog abandoned?

### ISSUE THREAD

**Issue by joemoraca** [Podcastindex-org/web-ui#36]
I see it has not been updated since Nov 6 as of now and the link for podcast episodes just seem to link to the jpeg for the logo.
![blog-image-links](https://user-images.githubusercontent.com/65661/102813366-ae199680-4396-11eb-9e0e-c23a7f025789.jpg)

**Comment by daveajones** [comment]
Pretty much.  Should probably remove the link.

**Comment by daveajones** [comment]
It's just easier to communicate through existing channels.

**Comment by joemoraca** [comment]
Well I would say it is important to have a blog / episode listing / show
notes page for any podcast - it's what normal people would find as the
"historical record". if it is the "extra work" someone might volunteer to
help out ... ;-)

Joe Moraca
386-288-9689
RVing With The Moracas
<https://www.youtube.com/channel/UC5xen7uKWUN93envrx0tTiA/>
