### ISSUE TITLE
`Mobile` filter should contain everything in iOS, Android, KaiOS, F-Droid, Sailfish

### ISSUE THREAD

**Issue by wakest** [Podcastindex-org/web-ui#361]
currently it contains a rather random selection of mobile apps.
https://podcastindex.org/apps?platforms=Mobile

**Comment by ericpp** [comment]
The quick fix for this would be to add the Mobile tag to any app that has the iOS, Android, KaiOS, F-Droid, and Sailfish tags in the `app.json` file: https://github.com/Podcastindex-org/web-ui/blob/master/server/data/apps.json
