### ISSUE TITLE
Add Funkwhale

### ISSUE THREAD

**Issue by MichaelHinrichs** [Podcastindex-org/web-ui#392]
https://www.funkwhale.audio/

**Comment by Marzal** [comment]
Has Funkwhale started using Podcasting 2.0 tags? :tada: 

Do you have more info?

**Comment by MichaelHinrichs** [comment]
Oh, does this project only take Podcasting 2.0?

**Comment by stevencrader** [comment]
You don't have to use any of the tags. Do use any of the Podcast Index APIs?

**Comment by daveajones** [comment]
We list apps/platforms that use either 2.0 tags or the Podcast Index API in some fashion.

**Comment by MichaelHinrichs** [comment]
Nevermind then.
