### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by MaxHillebrand** [Podcastindex-org/web-ui#64]
The health risks to users of white mode are dire, from bleeding eyes to permanent loss of sight.

Seriously, get a darkmode. :black_heart:

[I do have a rule to not contribute to free software projects that do not have a darkmode. But I love podcastindex.org too much, so I might give you some slack for now...]

**Comment by dellagustin** [comment]
Added with https://github.com/Podcastindex-org/web-ui/pull/221.
@daveajones , this issue could be closed.

**Comment by MaxHillebrand** [comment]
That's awesome, thanks!
