### ISSUE TITLE
Add anchor target for individual episodes

### ISSUE THREAD

**Issue by pedromvpg** [Podcastindex-org/web-ui#76]
Would be great if we could send out links to share specific episodes with each other.
Right now I can only link people to shows.

![image](https://user-images.githubusercontent.com/807505/118148501-9fcc2580-b3de-11eb-8bbe-363cf2b8148e.png)

Is there an episode detail page I'm missing?

**Comment by daveajones** [comment]
There’s not anything like that currently. Maybe it’s better to just put some web app links. Like linking over to podfriend, Podverse, etc.

**Comment by dergigi** [comment]
I'd love to have that too. Note that [pod.link](https://pod.link/) can link to individual episodes too.
